import turtle
wn=turtle.Screen()
t1=turtle.Turtle()
size=50
def giyuk(size):
    t1.fd(size)
    t1.rt(90)
    t1.fd(size)
oldPos=t1.pos()
oldHead=t1.heading()
giyuk(50)
t1.penup()
t1.goto(oldPos)
t1.pendown()
t1.setheading(oldHead +45)
giyuk(50)
t1.penup()
t1.goto(oldPos)
t1.pendown()
giyuk(50)
t1.penup()
t1.goto(oldPos)
t1.pendown()
giyuk(50)
t1.penup()
t1.goto(oldPos)
t1.pendown()
giyuk(50)
t1.penup()
t1.goto(oldPos)
t1.pendown()
t1.setheading(oldHead +90)
giyuk(50)
t1.penup()
t1.goto(oldPos)
t1.pendown()
t1.setheading(oldHead +180)
giyuk(50)
t1.penup()
t1.goto(oldPos)
t1.pendown()
oldPos=t1.heading()
t1.setheading(oldHead-90)
giyuk(50)
wn.exitonclick()
